// Notification Types
export const NOTIFICATION_TYPES = {
    LIKE: 0,
    COMMENT: 1,
    FOLLOW: 2,
    COMMENT_REPLY: 3,
    COMMENT_LIKE: 4,
    WELCOME: 5,
    SYSTEM: 6
};

// Notification Actions
export const NOTIFICATION_ACTIONS = {
    SET_NOTIFICATIONS: 'SET_NOTIFICATIONS',
    ADD_NOTIFICATION: 'ADD_NOTIFICATION',
    UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
    REMOVE_NOTIFICATION: 'REMOVE_NOTIFICATION',
    SET_UNREAD_COUNT: 'SET_UNREAD_COUNT',
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    MARK_AS_READ: 'MARK_AS_READ',
    MARK_ALL_AS_READ: 'MARK_ALL_AS_READ'
};
